// /form/FieldConfig.ts

// ─── All available field types ───
export type FieldType =
  // Inputs
  | "text"
  | "email"
  | "number"
  | "currency"
  | "password"
  | "url"
  | "tel"
  | "date"
  | "datetime-local"
  | "file"
  | "checkbox"
  | "radio-group"
  | "textarea"
  | "select"
  // Structural / visual blocks
  | "header"
  | "spacer";

// ─── Option shape for select, radio, checkbox ───
export interface FieldOption {
  label: string;
  value: string;
  checked?: boolean; // used for checkbox
  default?: boolean; // used for radio-group & select
}

// ─── Supported masking types ───
export type MaskType =
  | "creditCard"
  | "ssn"
  | "zip"
  | "usPostal"
  | "tel"
  | "email"
  | "url"
  | "currency"
  | "decimal"
  | "time"
  | "alphanumeric"
  | "slug"
  | "custom";

// ─── Field configuration ───
export interface FieldConfig {
  // Identity
  id: number;
  type: FieldType;

  // Label = user-facing text
  // For "header": displayed heading
  // For inputs: field label
  label: string;

  // Machine identifier
  // For structural blocks (header/spacer), can be autogenerated
  name: string;

  // ─── Layout & styling ───
  layout?: "full" | "half";
  align?: "start" | "center" | "end";
  justify?: "start" | "center" | "end" | "between";
  margin?: string;  // Tailwind margin utility (e.g. "mb-4")
  padding?: string; // Tailwind padding utility (e.g. "p-2")

  // ─── Common input props ───
  required?: boolean;
  placeholder?: string;

  // ─── Text validation ───
  minlength?: number;
  maxlength?: number;
  exactLength?: number;
  pattern?: string;
  maskType?: MaskType;

  // ─── Character restrictions ───
  alphaOnly?: boolean;
  noWhitespace?: boolean;
  uppercaseOnly?: boolean;
  lowercaseOnly?: boolean;

  // ─── Extra validation rules ───
  startsWith?: string;
  endsWith?: string;
  contains?: string;
  minWords?: number;
  maxWords?: number;
  allowedValues?: string[];
  disallowedValues?: string[];
  matchField?: string;
  customErrorMessage?: string;

  // ─── Number validation ───
  minValue?: number;
  maxValue?: number;
  step?: number | "any";
  noNegative?: boolean;
  positiveOnly?: boolean;
  integerOnly?: boolean;
  decimalPlaces?: number;

  // ─── Date validation ───
  minDate?: string; // "YYYY-MM-DD" or ISO datetime
  maxDate?: string;

  // ─── Options (checkbox / radio / select) ───
  options?: FieldOption[];
  orientation?: "vertical" | "horizontal";
  isMulti?: boolean;

  // ─── File uploads ───
  accept?: string;
  multiple?: boolean;
  maxFileSizeMB?: number;

  // ─── Textarea ───
  rows?: number;
  cols?: number;

  // ─── Header specific ───
  level?: "h1" | "h2" | "h3" | "h4" | "h5";

  // ─── Spacer specific ───
  spacerSize?: "sm" | "md" | "lg" | "xl" | number;
  hideOnMobile?: boolean;   // 🔥 NEW: allows toggle to hide spacer in mobile preview
}
